Add support for Longhorn model
rancher/image-build-opni-inference-service pull request #28
Opened 2022-08-17 20:50 UTC by AmartC

This PR adds support to the inferencing service to now load the Longhorn model from S3 and run inferencing.

2022-08-24 20:47 UTC, tybalex requested changes

2022-08-24 20:47 UTC, tybalex commented on opnilog-inference-service/start_opnilog_inference.py
> +    elif IS_LONGHORN_SERVICE:
pls merge L42 - L62 as the only difference is subject name.

2022-08-24 20:47 UTC, tybalex commented on opnilog-inference-service/start_opnilog_inference.py
> +    if IS_CONTROL_PLANE_SERVICE or IS_RANCHER_SERVICE or IS_LONGHORN_SERVICE:
all these if condition with 3 ors should be replaced by if service type is not workload.

2022-08-25 23:21 UTC, tybalex approved these changes

2022-08-29 17:45 UTC, sanjay920 approved these changes

2022-08-29 18:03 UTC, merged