Switch to use local training data
rancher/image-build-opni-inference-service pull request #8
Opened 2021-08-13 02:35 UTC by dbason

Just dump es data and use windows locally

2021-08-13 05:09 UTC, sanjay920 submitted a review, later dismissed

2021-08-13 20:21 UTC, AmartC requested changes
The NulogServer.py script also needs to be updated as well to use the updated environment variable names, S3_ENDPOINT, S3_ACCESS_KEY and S3_SECRET_KEY.

2021-08-17 04:05 UTC, tybalex commented on nulog-inference-service/NulogTrain.py
> +            shutil.rmtree(windows_folder_path)
@AmartC @dbason  should we remove the window folder? how do we reuse the dumped data, or simply dump from es every training run?

2021-08-17 05:07 UTC, tybalex approved these changes, later dismissed
look good!

2021-08-17 06:02 UTC, AmartC requested changes

2021-08-17 06:02 UTC, AmartC commented on nulog-inference-service/NulogTrain.py
> +            shutil.rmtree(windows_folder_path)
Upon thinking some more, we shouldn't be deleting the windows directory since that'll be used for persistent storing.

2021-08-18 20:14 UTC, AmartC approved these changes

2021-08-18 20:15 UTC, merged